open module feast {
    requires beast.pkgmgmt;
    requires beast.base;

    exports feast;

    provides beast.base.core.BEASTInterface with
        feast.mapping.DensityMapper,
        feast.operators.SmartRealOperator,
        feast.operators.BlockIntUniformOperator,
        feast.operators.BlockIntRandomWalkOperator,
        feast.operators.SmartScaleOperator,
        feast.operators.BlockScaleOperator,
        feast.operators.SmartRealRandomWalkOperator,
        feast.operators.DiscreteUniformJumpOperator,
        feast.fileio.TreeFromNewickFile,
        feast.fileio.TraitSetFromXSV,
        feast.fileio.RealParameterFromLabelledXSV,
        feast.fileio.logfileiterator.TraceLogFileState,
        feast.fileio.logfileiterator.DummyPosterior,
        feast.fileio.logfileiterator.TreeLogFileState,
        feast.fileio.logfileiterator.LogFileState,
        feast.fileio.logfileiterator.LogFileIterator,
        feast.fileio.logfileiterator.LogFileRealParameter,
        feast.fileio.TreeFromNexusFile,
        feast.fileio.RealParameterFromXSV,
        feast.fileio.AlignmentFromNexus,
        feast.fileio.TraitSetFromTaxonSet,
        feast.fileio.TaxonSetFromTree,
        feast.fileio.TipDatesFromTree,
        feast.fileio.AlignmentFromFasta,
        feast.fileio.AlignmentFromFile,
        feast.simulation.GPSimulator,
        feast.simulation.SimulatedAlignment,
        feast.simulation.ShuffledAlignment,
        feast.function.Sequence,
        feast.function.SampleAges,
        feast.function.Reverse,
        feast.function.Concatenate,
        feast.function.TraitSetAsFunction,
        feast.function.MetadataAsFunction,
        feast.function.Interleave,
        feast.function.LoggableFunction,
        feast.function.Slice,
        feast.function.UniqueElementCount,
        feast.function.Scale,
        feast.modelselect.DirichletProcessOperator,
        feast.modelselect.ModelSelectionParameter,
        feast.modelselect.DirichletProcessPrior,
        feast.nexus.TreesBlock,
        feast.nexus.BasicNexusParser,
        feast.nexus.NexusBuilder,
        feast.nexus.NexusBlock,
        feast.nexus.NexusWriter,
        feast.nexus.CharactersBlock,
        feast.nexus.TaxaBlock,
        feast.expressions.ExpCalculatorDistribution,
        feast.expressions.ExpCalculator,
        feast.expressions.parser.ExpressionParser,
        feast.expressions.parser.ExpressionVisitor,
        feast.expressions.parser.ExpressionListener,
        feast.expressions.parser.ExpressionBaseVisitor,
        feast.expressions.parser.ExpressionBaseListener,
        feast.expressions.parser.ExpCalculatorVisitor,
        feast.expressions.parser.ExpressionLexer,
        feast.expressions.ExpCalculatorParametricDistribution,
        feast.parameter.RealParameterFromFunction,
        feast.parameter.IntegerParameterFromFunction,
        feast.parameter.TimeParameter,
        feast.parameter.RandomRealParameter,
        feast.popmodels.ShiftedPopulationModel,
        feast.popmodels.CompoundPopulationModel,
        feast.popmodels.ExpressionPopulationModel;
}
